site_name: Design Log
theme:
  name: material

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.tasklist
  - pymdownx.arithmatex

plugins:
  - search
  - mermaid2
