site_name: Group 24 Capstone
site_url: https://onsetbot.com/
extra:
  cname: onsetbot.com
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"   
      scheme: default
      primary: grey
      accent: deep purple
      toggle:
        icon: octicons/moon-16
        name: Switch to dark mode
  features:
    - content.code.copy
    - navigation.footer
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
  icon:
    logo: fontawesome/solid/volleyball
  favicon: images/onsetbot.png

markdown_extensions:
  - admonition
  - pymdownx.superfences:
      custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist
  - pymdownx.arithmatex
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.saneheaders:
  - pymdownx.fancylists:
      inject_style: true


plugins:
  - search
  - mermaid2:

nav:
  - Home: index.md
  - Logs:
    # - Week 10: logs/week-10.md
    # - Week 09: logs/week-09.md
    # - Week 08: logs/week-08.md
    # - Week 07: logs/week-07.md
    # - Week 06: logs/week-06.md
    # - Week 05: logs/week-05.md
    - Week 04: logs/week-04.md
    - Week 03: logs/week-03.md
    - Week 02: logs/week-02.md
    - Week 01: logs/week-01.md
      
      
